---
version: '3.7'
services:
  redis:
    image: redis:7.0.15
    container_name: gate_redis
    ports:
      - 4555:6379
    # expose:
    #   - ${REDIS_PORT}
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./redis_data:/data\
    # command: redis-server --requirepass ${REDIS_PASS}
    restart: always
    networks:
      - proxy

  db:
   image: mariadb:11.4.1-rc-jammy
   restart: always
   container_name: gate_db
   ports:
    - ${DB_PORT}:${DB_PORT}
   env_file:
    - .db.env
   command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
   networks:
    - proxy

  backend:
    depends_on:
      - redis
      - db
    # image: ${REGISTRY_URL}
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gate
    restart: unless-stopped
    volumes:
      - ./logs:/home/node/logs
      - /etc/localtime:/etc/localtime
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 700M
        reservations:
          cpus: '0.15'
          memory: 300M
    expose:
      - ${APP_PORT}
    env_file:
      - .env
    networks:
      - proxy

networks:
  proxy:
    external: true